# Generated by Django 3.2.8 on 2021-10-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug_api.bug')),
            ],
        ),
    ]
