# Generated by Django 3.2.8 on 2021-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='summary',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
